name: CI

on:
  pull_request:
    branches: [ dev, main ]
  push:
    branches: [ dev, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: voda_agents_test
        # Healthcheck so the job waits until PG is ready
        options: >-
          --health-cmd="pg_isready -U postgres -d voda_agents_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10
        ports:
          - 5432:5432
    env:
      NODE_ENV: test
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/voda_agents_test
      JWT_EXPIRES_IN: 15m
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      # Generate a fresh random secret for this job only
      - name: Generate JWT secret
        run: |
          node -e "console.log('JWT_ACCESS_SECRET=' + require('crypto').randomBytes(32).toString('hex'))" >> $GITHUB_ENV
          echo "JWT_EXPIRES_IN=15m" >> $GITHUB_ENV

      - run: echo "JWT_EXPIRES_IN=15m" >> $GITHUB_ENV

      - name: Install
        run: npm ci
      - run: npx prisma generate
      - run: npx prisma migrate deploy
      - name: Run tests
        run: npm test
